### ISSUE TITLE
Images with newly changed Creative Commons licenses not available for upload

### ISSUE THREAD

**Issue by SiobhanLeachman** [kaldari/iNaturalist2Commons#9]
I've been using this wonderful tool frequently. I've also been managing to convince some users on iNaturalist to change the licenses on their images to a more open license. However the iNaturalist2Commons tool doesn't appear to immediately pick these images up and make them available for upload. See for example https://www.inaturalist.org/observations/66320770 and https://commons.wikimedia.org/wiki/Category:Mycopsylla_fici. Is there a way to resolve this?

**Comment by Rudolphous** [comment]
Should be fixed by:
https://github.com/kaldari/iNaturalist2Commons/pull/10/commits

@kaldari Can you review/test this ?

**Comment by kaldari** [comment]
Seems to work, although I'm curious why that key change would fix it. I would have thought it was some kind of caching issue.

**Comment by kaldari** [comment]
@Rudolphous - It looks like this change causes other freely licensed images to not appear in the results. I reverted the live version for now. Compare https://api.inaturalist.org/v1/observations?license_code=cc0%2Ccc-by%2Ccc-by-sa&quality_grade=research&taxon_id=50340&per_page=84 with https://api.inaturalist.org/v1/observations?photo_license=cc0%2Ccc-by%2Ccc-by-sa&quality_grade=research&taxon_id=50340&per_page=84. The license_code parameter is strangely undocumented, so I don't actually know what it is supposed to do. How did you discover it?

**Comment by Rudolphous** [comment]
In iNaturalist there are 3 licenses: license for observation, license for photo and license for sounds. Looks like the photo license parameter is broken on the API and causes sometimes photo's to be skipped? Think with my change the photo's are pulled by free licensed observations and then filtered on photo license with already existing code. This fixes the missing photo case but can cause maybe others photo's missing? Not sure if just more observations needs to be pulled or missing photo case must be fixed on iNaturalist API level?

**Comment by kaldari** [comment]
@Rudolphous - The parameter for the observation license is `license`, not `license_code`. It looks like `license_code` isn't a recognized parameter, so it just gets ignored, which explains why it returns a lot more images. I think the real problem is caching on the API side rather than the parameters used by iNaturalist2Commons. And since we can't do anything about the caching on the API side, I'm going to reclose the bug report.

@SiobhanLeachman - I think the issue here is that iNaturalist is caching their API results. This means that if you wait a day or two after the observation is created on iNaturalist it should show up within the iNaturalist2Commons interface. Unfortunately there's nothing else we can do on our end.
